name: Zola to Azure

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Build
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          PAGES_BRANCH: az-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZOLA_ENV: prod
          
  deploy_azure:
    needs: build
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout az-pages
        uses: actions/checkout@v4
        with:
          ref: az-pages
      - name: Deploy (Azure)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_PEBBLE_063B0A203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/" # Built app content directory - optional